# Default values for amko.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: amko
  pullPolicy: IfNotPresent

configs:
  gslbLeaderHost: ""
  controllerVersion: "18.2.9"
  gslbLeaderSecret: "gslb-avi-secret"
  memberClusters:
    - clusterContext: "cluster1-admin"
    - clusterContext: "cluster2-admin"
  refreshInterval: 1800
  gslbLeaderCredentials:
    username: "admin"
    password: "avi123"
  domainNames:
    - foo.com
  clusterMembers:
    secret: gslb-config-secret
    key: gslb-members
  logLevel: "INFO"

gdpConfig:
  # appSelector takes the form of:
  # appSelector:
  #   label:
  #     app: gslb   <example label key-value for an ingress/service type LB>
  appSelector:

  # namespaceSelector takes the form of:
  # namespaceSelector:
  #   label:
  #     ns: gslb   <example label key-value for namespace>
  namespaceSelector:

  # list of all clusters that the GDP object will be applied to, can take any/all values
  # from .configs.memberClusters
  matchClusters:
    - "cluster1-admin"
    - "cluster2-admin"

  # list of all clusters and their traffic weights, if unspecified, default weights will be
  # given
  trafficSplit:
    - cluster: "cluster1-admin"
      weight: 8
    - cluster: "cluster2-admin"
      weight: 2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

service:
  type: ClusterIP
  port: 80

persistentVolumeClaim: ""
mountPath: "/log"
logFile: "amko.log"